---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "postgres-config"
  labels:
    app: "aspire"
    component: "postgres"
data:
  POSTGRES_HOST_AUTH_METHOD: "{{ .Values.config.postgres.POSTGRES_HOST_AUTH_METHOD }}"
  POSTGRES_INITDB_ARGS: "{{ .Values.config.postgres.POSTGRES_INITDB_ARGS }}"
  POSTGRES_USER: "{{ .Values.config.postgres.POSTGRES_USER }}"
