---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "postgres-secrets"
  labels:
    app: "aspire"
    component: "postgres"
stringData:
  POSTGRES_PASSWORD: "{{ .Values.secrets.postgres.postgres_password }}"
type: "Opaque"
