---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "existingapi-secrets"
  labels:
    app: "aspire"
    component: "existingapi"
stringData:
  ConnectionStrings__postgres_books_db: "Host=postgres;Port=5432;Username=postgres;Password={{ .Values.secrets.existingapi.postgres_password }};Database=postgres-books-db"
type: "Opaque"
